name: bdsl-pre
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - pandas>=2.0
  - opencv
  - scipy>=1.11
  - pytorch
  - pip:
      - mediapipe>=0.10
      - PyYAML>=6.0
      - tqdm>=4.66
